name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: rspp777/weatherui:v2.0.0
    
#     - run: docker build . --file Dockerfile --tag weatherui:$(date +%s)
#            docker tag v2.0.0 rspp777/weatherui
#            docker push rspp777/weatherui
